In [21]:
import pandas as pd
import numpy as np
import seaborn as sns
from pathlib import Path as P
import matplotlib.pyplot as plt
import plotly.express as px
import pickle
from sklearn.preprocessing import StandardScaler, MinMaxScaler

建模的思路：
1. 对每一种（小区，强度）都建立一个线性回归模型，预测所有的Y变量；


In [14]:
df=pd.read_csv('./问题3-附件14.csv')
YEAR,BLOCK,INTENSITY,SOC,SIC,STC,ALLN,CN=df.columns


In [28]:
NUMERIC=[SOC,SIC,STC,ALLN,CN]
scaler=StandardScaler()
scaler.fit(df[NUMERIC])
df[NUMERIC]=scaler.transform(df[NUMERIC])

In [29]:
df[NUMERIC]

SOC土壤有机碳  SIC土壤无机碳   STC土壤全碳       全氮N    土壤C/N比
0  -1.614686  1.445963  0.525585 -2.058148  1.784696
1  -1.086067  1.195153  0.608396 -0.335492  0.503674
2  -0.846917  1.562355  1.196299 -0.818160  1.632568
3  -1.435877  1.066942  0.216713 -0.815889  0.590486
4  -1.697971  0.505872 -0.609258 -1.328727  0.395869
5  -0.347215  2.308460  2.400484  0.322249  0.891976
6  -0.406545 -0.286491 -0.612651 -0.349285 -0.213506
7  -1.922488  0.514825 -0.756164 -0.586079 -0.253432
8  -0.728012  0.726718  0.322602 -0.284953  0.164965
9  -0.554554  1.231085  1.021596 -0.767226  1.222701
10  0.000265  1.263914  1.447554 -1.826518  2.434236
11 -1.715103  0.864002 -0.211138 -1.505600  1.073046
12 -1.167833  0.219368 -0.566259 -0.773713  0.140593
13  0.845574  1.526542  2.340008 -0.347652  1.484297
14 -1.279751  0.747609 -0.039684 -2.078592  1.500481
15 -0.257034  0.881908  0.829996 -0.489424  0.633709
16 -0.753505  1.732467  1.456490 -0.460294  0.980941
17 -0.182109  0.672939  0.643142 -0.806196  0.961380
18  0.037985  0.138788  0.185523 -0.333405  0.230399
19 -1.449363  1.428056  0.620803 -1.959702  1.947152
20  0.028344 -0.129809 -0.128811 -0.602693  0.204635
21 -0.687226  1.284804  0.990243 -0.850290  1.145693
22  0.477562 -0.004464  0.329175 -0.577789  0.446139
23 -0.472561  0.496918  0.238259 -0.661583  0.483159
24  0.614059 -0.780412 -0.463855  0.263030 -0.472703
25 -0.372527  0.077110 -0.172461  0.430104 -0.248877
26 -0.244594  0.097006 -0.060126  0.051034 -0.084227
27  0.291921 -0.794140 -0.705068  0.069155 -0.482564
28  0.998721  0.065173  0.773724  0.338675  0.229491
29 -0.353054 -0.434220 -0.744380 -0.062192 -0.351130
30 -0.966597 -0.726295 -1.508321 -0.394725 -0.725434
31  0.542108  0.252196  0.668271 -0.994076  1.420813
32 -0.522637 -0.290968 -0.699040  0.036182 -0.431575
33  0.444663  0.168632  0.504367 -0.056447  0.445737
34 -0.176407 -0.299722 -0.466709 -0.100316 -0.165101
35  0.535986 -0.458095 -0.149404  0.135977 -0.047947
36  0.066401 -0.667004 -0.717339  0.374028 -0.713805
37  0.659019 -0.374531  0.032410  0.591555 -0.377634
38  0.548330 -1.007228 -0.769602  0.699519 -0.951602
39 -0.000436 -0.452126 -0.518057  0.138720 -0.446035
40  1.272281  0.437230  1.391273  1.122305  0.121541
41 -0.070666 -0.720724 -0.874802  0.481503 -0.818351
42  0.143098 -1.150480 -1.217304  0.453178 -1.060543
43 -0.938582  1.201241  0.718605 -0.806618  1.117191
44 -0.198423 -1.681706 -2.064697  0.183789 -1.400211
45  0.494007  0.114913  0.477390  0.671667 -0.060271
46  1.284308 -0.696848  0.101003  0.885641 -0.497789
47  1.823743 -0.637160  0.546952  1.658359 -0.619371
48  1.038093 -1.413813 -0.892375  1.277783 -1.372190
49  0.614908 -1.022610 -0.740613  1.055436 -1.206927
50  1.335782 -1.572303 -0.865492  1.895745 -1.595142
51  0.741577 -1.328506 -1.002244  0.549453 -1.109814
52  2.569658 -0.109288  1.673574  1.988832 -0.512608
53 -0.076408 -1.615619 -1.903609  0.879863 -1.701752
54 -0.102949 -1.489414 -1.777664  0.626180 -1.537362
55 -0.083820  0.826201  0.887451 -0.522189  0.552446
56 -0.280033 -2.015185 -2.503706  0.532172 -1.868875
57  1.135585 -0.510591  0.210191  1.334694 -0.878115
58  1.393492 -1.149961 -0.341451  1.716486 -1.293309
59  3.054479 -1.234676  0.724205  2.790662 -1.241814

In [30]:
scaler.mean_, scaler.scale_

(array([14.92006485,  7.51246398, 22.43252883,  1.82556675, 13.00669993]),
 array([1.7068166 , 2.79228173, 2.43835697, 0.21700343, 2.45867866]))

In [32]:
df[YEAR] -= df[YEAR].min()
df[YEAR].unique()

array([0, 2, 4, 6, 8], dtype=int64)

In [10]:
df[BLOCK].unique(),df[INTENSITY].unique()

(array(['HGI', 'LGI', 'MGI', 'NG'], dtype=object),
 array(['G13', 'G20', 'G9', 'G12', 'G18', 'G6', 'G11', 'G16', 'G8', 'G17',
        'G19', 'G21'], dtype=object))

In [33]:
df_list=[(info, df.drop(columns=[BLOCK, INTENSITY])) for info, df in df.groupby([BLOCK, INTENSITY])]
df_list

[(('HGI', 'G13'),
      year  SOC土壤有机碳  SIC土壤无机碳   STC土壤全碳       全氮N    土壤C/N比
  0      0 -1.614686  1.445963  0.525585 -2.058148  1.784696
  12     2 -1.167833  0.219368 -0.566259 -0.773713  0.140593
  24     4  0.614059 -0.780412 -0.463855  0.263030 -0.472703
  36     6  0.066401 -0.667004 -0.717339  0.374028 -0.713805
  48     8  1.038093 -1.413813 -0.892375  1.277783 -1.372190),
 (('HGI', 'G20'),
      year  SOC土壤有机碳  SIC土壤无机碳   STC土壤全碳       全氮N    土壤C/N比
  1      0 -1.086067  1.195153  0.608396 -0.335492  0.503674
  13     2  0.845574  1.526542  2.340008 -0.347652  1.484297
  25     4 -0.372527  0.077110 -0.172461  0.430104 -0.248877
  37     6  0.659019 -0.374531  0.032410  0.591555 -0.377634
  49     8  0.614908 -1.022610 -0.740613  1.055436 -1.206927),
 (('HGI', 'G9'),
      year  SOC土壤有机碳  SIC土壤无机碳   STC土壤全碳       全氮N    土壤C/N比
  2      0 -0.846917  1.562355  1.196299 -0.818160  1.632568
  14     2 -1.279751  0.747609 -0.039684 -2.078592  1.500481
  26     4 -0.244594  0.0970

In [35]:
pickle.dump(df_list, open('问题3-分组数据.pkl','wb'))
pickle.dump(scaler, open('问题3-scaler.pkl', 'wb'))
pickle.dump(NUMERIC, open('问题3-因变量列名.pkl', 'wb'))

In [38]:
def plotBlockIntensity(df_list, i):
    info,df2=df_list[i]
    return px.line(df2,x=YEAR,y=NUMERIC).update_layout(xaxis_title='年份', yaxis_title='归一化后各变量取值',
                                                legend_title='土壤化学性质',title=f'放牧强度{info[0]}下小区{info[1]}的土壤性质随时间变化图')

In [39]:
len(df_list)

12

一共有12种（小区，强度）的组合，故只选取几个作为样本。

In [40]:
plotBlockIntensity(df_list, 0)

In [43]:
plotBlockIntensity(df_list, 4)

In [44]:
plotBlockIntensity(df_list, 7)

In [45]:
plotBlockIntensity(df_list, 10)